name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: wget https://github.com/ZProtons/Cloudron-Setup-Modified/blob/main/cloudron-setup
    - name: Changing Permissions
      run: chmod +x ./cloudron-setup
    - name: Installing nginx
      run: sudo apt purge nginx nginx-common nginx-core
    - name: Installing docker (1/2)
      run: sudo apt install -y runc containerd docker docker.io
    - name: Installing nodejs
      run: sudo apt install nodejs
    - name: Installing
      run: sudo ./cloudron-setup --provider generic
